import { useId } from 'react';
import { categories, consumers, deviations, owners, relations, representations, sources, strengths, type Gene } from './model';
export function Choices({ label, options, value, onChange, multiple=false }: {label:string; options:string[]; value:string|string[]; onChange:(value:string)=>void; multiple?:boolean}) {
  const id=useId();
  return <fieldset className="gene-choices"><legend>{label}</legend><div>{options.map(option=><label key={option}><input type={multiple?'checkbox':'radio'} name={id} checked={Array.isArray(value)?value.includes(option):value===option} onChange={()=>onChange(option)} /><span>{option}</span></label>)}</div></fieldset>;
}
export const questions = ["", "What’s one design decision your team shouldn’t have to rediscover every time?", 'Why does this decision exist?', 'Make the source and owner visible.', 'What kind of design knowledge is this?', 'What does this decision depend on or inform?', 'Make the boundary visible.', 'Where should this knowledge travel?'];
export function Fields({step,gene:g,update}:{step:number;gene:Gene;update:(patch:Partial<Gene>)=>void}) {
  const prefix=useId();
  const text=(label:string,key:keyof Gene,placeholder='')=><label className="gene-field">{label}<input value={String(g[key])} maxLength={1000} onChange={e=>update({[key]:e.target.value})} placeholder={placeholder}/></label>;
  return <>
    {step===1 && <><label className="gene-field" htmlFor="gene-decision">Your recurring decision</label><textarea id="gene-decision" value={g.decision} maxLength={5000} rows={5} onChange={e=>update({decision:e.target.value})} aria-describedby="gene-decision-help"/><p id="gene-decision-help" className="gene-help">Good candidates are repeated, important, and currently depend on someone remembering them.</p><p className="gene-teaching">This is the organizational knowledge you want future work to inherit.</p></>}
    {step===2 && <><label className="gene-field" htmlFor="gene-intent">The outcome this protects</label><textarea id="gene-intent" value={g.intent} maxLength={5000} rows={5} onChange={e=>update({intent:e.target.value})} aria-describedby="gene-intent-help"/><p id="gene-intent-help" className="gene-help">What user or product outcome is this decision protecting?</p><details className="gene-detail"><summary>See an example of intent</summary><p>Prevent users from accidentally taking irreversible actions they don’t fully understand.</p></details></>}
    {step===3 && <><Choices label="Where does this knowledge live today?" options={sources} value={g.source} onChange={source=>update({source})}/>{g.source==='Other' && text('Describe the source','sourceOther')}{g.source==='Someone’s head' && <p className="gene-teaching">That’s organizational design intelligence. It exists—it just isn’t infrastructure yet.</p>}<Choices label="Who should own this decision?" options={owners} value={g.owner} onChange={owner=>update({owner})}/>{g.owner==='Other' && text('Name the owner','ownerOther')}<p className="gene-help">Authority can be distributed. You’re identifying a source and owner for this decision, not choosing one universal home for everything.</p></>}
    {step===4 && <><Choices label="Choose one primary classification" options={representations} value={g.representation} onChange={representation=>update({representation})}/><p className="gene-teaching">Human-readable guidance and machine-consumable structure can represent the same organizational knowledge.</p><p className="gene-help">Not sure is a valid starting point. Classification here does not impose a file format.</p></>}
    {step===5 && <><p className="gene-help">Add the knowledge you actually connect to this decision. Zero relationships is fine for a first draft.</p><p className="gene-help">Think about components, patterns, content, foundations, or rules this decision relies on or affects.</p><div className="gene-relationship-examples"><p className="gene-help">Examples only—not connections to your Gene:</p><ul aria-label="Example knowledge names"><li>Button</li><li>Modal</li><li>Action labels</li><li>Destructive color</li></ul></div>{g.relationships.map((r,index)=><fieldset className="gene-relationship" key={index}><legend>Connection {index+1}</legend><label className="gene-field" htmlFor={`${prefix}-${index}`}>Knowledge name<input id={`${prefix}-${index}`} value={r.target} maxLength={200} placeholder="For example: Button or Action labels" onChange={e=>update({relationships:g.relationships.map((item,i)=>i===index?{...item,target:e.target.value}:item)})}/></label><div className="gene-two"><label className="gene-field">Category (optional)<select value={r.category} onChange={e=>update({relationships:g.relationships.map((item,i)=>i===index?{...item,category:e.target.value}:item)})}><option value="">Unspecified</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="gene-field">Relationship (optional)<select value={r.type} onChange={e=>update({relationships:g.relationships.map((item,i)=>i===index?{...item,type:e.target.value}:item)})}><option value="">Unspecified</option>{relations.map(c=><option key={c}>{c}</option>)}</select></label></div><button type="button" className="gene-text-button" onClick={()=>{update({relationships:g.relationships.filter((_,i)=>i!==index)}); document.getElementById('gene-add-relationship')?.focus();}}>Remove connection {index+1}</button></fieldset>)}<button id="gene-add-relationship" type="button" className="gene-secondary" disabled={g.relationships.length>=100} onClick={()=>update({relationships:[...g.relationships,{target:'',category:'',type:''}]})}>Add a relationship +</button><p className="gene-teaching">Connected knowledge is more useful than another isolated document.</p></>}
    {step===6 && <><Choices label="How strongly should this decision apply?" options={strengths} value={g.strength} onChange={strength=>update({strength})}/><Choices label="What should happen when someone needs to deviate?" options={deviations} value={g.deviation} onChange={deviation=>update({deviation})}/>{text('Who reviews exceptions? (optional)','reviewer')}<p className="gene-teaching">Governance isn’t making every decision automatic. It’s making the boundary visible.</p><p className="gene-help">These choices describe your governance intent. They do not technically enforce it.</p></>}
    {step===7 && <><Choices label="Choose the people and tools that should consume it" options={consumers} value={g.consumers} multiple onChange={c=>update({consumers:g.consumers.includes(c)?g.consumers.filter(v=>v!==c):[...g.consumers,c]})}/>{g.consumers.includes('Other') && text('Name the other consumer','consumerOther')}<p className="gene-teaching">The AI tool is replaceable. Your organization’s design intelligence isn’t.</p><p className="gene-help">One system, multiple consumers. An adapter translates relevant organizational knowledge for a particular consumer. The adapter doesn’t own the knowledge.</p></>}
  </>;
}
