import type { ReactNode } from 'react';
import { Link } from 'react-router';
import { Button } from '../../src/components/Button';
import { activityUrl } from './model';
import qr from './qr.json';
export const domains=['Principles','Foundations','Components','Patterns','Content','Rules','Governance'];
const Reveal=({at,beat,children,className=''}:{at:number;beat:number;children:ReactNode;className?:string})=><div className={`pr-reveal ${className}`} data-visible={beat>=at} aria-hidden={beat<at} inert={beat<at}>{children}</div>;
const Label=({children}:{children:ReactNode})=><p className="pr-label">{children}</p>;
const Statement=({children}:{children:ReactNode})=><h1 className="pr-display">{children}</h1>;
function QR({name}:{name:keyof typeof qr}){const data=qr[name];return <figure className="pr-qr"><svg viewBox={`0 0 ${data.size} ${data.size}`} role="img" aria-label={`QR code for ${data.url}`} shapeRendering="crispEdges"><rect width={data.size} height={data.size} fill="#fff"/><path d={data.path} fill="#16131e"/></svg><figcaption>{data.url.replace('https://','')}</figcaption></figure>;}
function Flow({items,beat=99}:{items:{title:string;copy?:string}[];beat?:number}){return <div className="pr-flow">{items.map((item,i)=><Reveal at={i+1} beat={beat} key={item.title}><span className="pr-flow-node"/><h2>{item.title}</h2>{item.copy&&<p>{item.copy}</p>}</Reveal>)}</div>;}
function Orbit({center,labels,beat,base=1}:{center:string;labels:string[];beat:number;base?:number}){return <div className="pr-orbit"><svg viewBox="0 0 1408 440" aria-hidden="true">{labels.map((_,i)=>{const left=i%2===0,y=70+Math.floor(i/2)*145;return <path key={i} data-visible={beat>=base+Math.floor(i/2)} d={`M704 220 L${left?370:1038} ${y}`} />;})}</svg><strong className="pr-orbit-center">{center}</strong>{labels.map((label,i)=><Reveal key={label} at={base+Math.floor(i/2)} beat={beat} className={`pr-orbit-item pr-orbit-${i}`}><span>{label}</span></Reveal>)}</div>;}
export function Scene({scene,beat}:{scene:number;beat:number}){
  switch(scene){
    case 1:return <div className="pr-title-scene"><Label>DDX / A 60-minute workshop</Label><h1 className="pr-xl">THE DESIGN<br/><em>GENOME</em></h1><p className="pr-statement">Building design systems for humans<br/>and the AI era.</p><div className="pr-title-lines" aria-hidden="true"><i/><i/><i/></div></div>;
    case 2:return <div className="pr-intro-scene"><Label>The person guiding the room</Label><Statement>Ivan Barriga</Statement><p className="pr-statement">Head of Product Design &amp; UX</p><div className="pr-topics">{['Design systems','AI-assisted creation','Product design','Design leadership'].map(x=><span key={x}>{x}</span>)}</div><p className="pr-body pr-limit">Exploring how organizational design intelligence survives the tools creating the interface.</p></div>;
    case 3:return <div className="pr-stacked"><Statement>AI makes creating UI<br/>nearly free.</Statement><Reveal at={2} beat={beat}><Statement>It also makes creating<br/><em>inconsistent UI</em> nearly free.</Statement></Reveal></div>;
    case 4:return <><h1 className="pr-title">Who creates now?</h1><div className="pr-creators"><div>{['Designer','Engineer','PM','AI coding tool','Prototyping tool','Agent'].map((x,i)=><Reveal key={x} at={i===0?1:i<3?2:3} beat={beat}><span>{x}</span></Reveal>)}</div><div className="pr-converge" aria-hidden="true">→</div><strong>Product /<br/>interface</strong></div><p className="pr-body pr-limit">Consistency can no longer depend on every creator remembering everything the organization knows.</p></>;
    case 5:return <><h1 className="pr-title">The Button</h1><div className="pr-button-scene"><div className="pr-button-object"><div className="pr-forma-scale"><Button variant="destructive">Delete project</Button></div></div><div className="pr-questions">{['When is destructive treatment appropriate?','Does this require confirmation?','What should the confirmation explain?','What should the action be called?','Who can approve an exception?'].map((x,i)=><Reveal key={x} at={i+2} beat={beat}><p>{x}</p></Reveal>)}</div></div><Reveal at={7} beat={beat}><p className="pr-statement">A component can tell us what exists.</p></Reveal><Reveal at={8} beat={beat}><p className="pr-body">It doesn’t necessarily carry every decision surrounding its use.</p></Reveal></>;
    case 6:return <><Statement>Most drift isn’t irrational.</Statement><Reveal at={2} beat={beat}><h2 className="pr-title pr-limit">Products drift through hundreds of individually reasonable decisions.</h2></Reveal><svg className="pr-drift" viewBox="0 0 1408 170" aria-hidden="true">{[0,1,2,3,4].map(i=><g key={i}><path d={`M0 85 L280 85 L570 ${65+i*10} L850 ${40+i*22} L1400 ${10+i*37}`} /><circle cx="850" cy={40+i*22} r="5"/></g>)}</svg></>;
    case 7:return <div className="pr-centered"><Label>Organizational design intelligence</Label><Statement>What if the system<br/>carried the knowledge<br/><em>forward?</em></Statement><p className="pr-body">Not another AI tool.</p></div>;
    case 8:return <><Label>Definition / Design Genome</Label><h1 className="pr-definition">Design Genome is a methodology for structuring an <em>organization’s design intelligence</em> so <em>humans and AI</em> can create from the <em>same governed system.</em></h1><p className="pr-body">Additive to your existing system. Human-facing experiences remain first-class.</p></>;
    case 9:return <><Label>The core model</Label><h1 className="pr-title">Design knowledge, carried forward.</h1><Flow beat={beat} items={[{title:'Intent',copy:'What are we trying to create?'},{title:'Intelligence',copy:'What does our organization know?'},{title:'Inheritance',copy:'What should the result carry forward?'}]}/><Reveal at={3} beat={beat}><p className="pr-body pr-bottom-note">Human or machine objective → organizational design intelligence → a result that inherits design decisions.</p></Reveal></>;
    case 10:return <><h1 className="pr-title">Fewer guesses.</h1><div className="pr-comparison"><div><Label>Without organizational intelligence</Label><p>Intent</p><span>↓</span><p>Documentation + memory + assumptions</p><span>↓</span><strong>Reasonable guesses</strong></div><Reveal at={2} beat={beat}><Label>With Design Genome</Label><p>Intent</p><span>↓</span><p>Relevant organizational intelligence</p><span>↓</span><strong>Fewer organizational decisions are guesses</strong></Reveal></div><Reveal at={3} beat={beat}><p className="pr-body">The goal isn’t to make AI the designer.</p></Reveal><Reveal at={4} beat={beat}><p className="pr-body pr-purple">It’s to make organizational knowledge available when something gets created.</p></Reveal></>;
    case 11:return <div className="pr-resource"><div><Label>Experience it</Label><Statement>Same task.</Statement><Reveal at={2} beat={beat}><h2 className="pr-display"><em>More knowledge<br/>to work from.</em></h2></Reveal><Reveal at={3} beat={beat}><Link className="pr-action" to={activityUrl('/workshop')}>Experience it →</Link><p className="pr-body">Delete project · Create project · Analytics</p></Reveal></div><Reveal at={3} beat={beat}><QR name="workshop"/></Reveal></div>;
    case 12:return <><h1 className="pr-title">Four complementary capabilities.</h1><div className="pr-capabilities"><span className="pr-governance">Governance crosses every capability</span><strong>Design<br/>Intelligence</strong><div>{['Human-readable','Machine-readable','Executable','Connectable'].map((x,i)=><Reveal key={x} at={i+1} beat={beat}><span>{x}</span></Reveal>)}</div></div><p className="pr-body">Capabilities, not sequential maturity levels.</p></>;
    case 13:return <><h1 className="pr-title">What is in a Genome?</h1><div className="pr-domains">{domains.map((x,i)=><Reveal key={x} at={Math.min(4,1+Math.floor(i/2))} beat={beat}><span>{x}</span></Reveal>)}</div><p className="pr-statement">Different knowledge. Appropriate representations.<br/><em>Connected authority.</em></p><p className="pr-body">These sources do not need to live in one file.</p></>;
    case 14:return <div className="pr-two-columns"><div><Label>The reference implementation</Label><h1 className="pr-xl">FORMA</h1><p className="pr-statement">A fictional product used<br/>to test the methodology.</p><p className="pr-body">One implementation.<br/>Not the methodology itself.</p></div><Reveal at={2} beat={beat}><pre className="pr-tree">{'genome/\n├── principles/\n├── foundations/\n├── components/\n├── patterns/\n├── content/\n├── rules/\n└── governance/'}</pre></Reveal></div>;
    case 15:return <><h1 className="pr-title">The adapter</h1><div className="pr-adapter" data-phase={beat===1?'direct':beat===2?'adapter':'branches'}><div className="pr-authority">Design Genome<small>Organizational knowledge</small></div><span className="pr-arrow">→</span><div className="pr-adapter-branches">{['Codex','Claude Code','Figma'].map((x,i)=><Reveal key={x} at={i===0?1:3} beat={beat}><span className="pr-adapter-box" data-visible={beat>=2}>Adapter</span><span aria-hidden="true">→</span><div>{x}<small>{i===0?'Real reference implementation':'Conceptual example only'}</small></div></Reveal>)}</div></div><p className="pr-body">An adapter translates relevant Design Genome knowledge into a form a particular consumer can use.</p><Reveal at={4} beat={beat}><p className="pr-body">The adapter doesn’t own the knowledge. Validation and enforcement remain separate.</p></Reveal><Reveal at={5} beat={beat}><p className="pr-statement pr-purple">The AI tool is replaceable.<br/>Your organization’s design intelligence isn’t.</p></Reveal></>;
    case 16:return <><Label>Real proof / Existing Forma + Codex reference</Label><h1 className="pr-title">From a task to relevant intelligence.</h1><div className="pr-pipeline">{[['Task','Create a project form.'],['Select','Form'],['Resolve','Input · Button · Stack · relevant rules'],['Adapt','Codex context'],['Create','UI']].map(([label,copy])=><div key={label}><Label>{label}</Label><p>{copy}</p></div>)}</div><p className="pr-body">Supplied context does not certify the result. Implementation still needs judgment and review.</p><div className="pr-links"><Link to={activityUrl('/reference/machine-context')}>Inspect real machine context →</Link><a href="/reference/forma/" target="_blank" rel="noreferrer">Open executable Forma showcase ↗</a></div><p className="pr-micro">The showcase opens separately. The deck stays here.</p></>;
    case 17:return <div className="pr-resource pr-your-turn"><div><Label>Your turn</Label><h1 className="pr-title">Enough about Forma.</h1><Reveal at={2} beat={beat}><p className="pr-statement">Think about your organization.</p></Reveal><Reveal at={3} beat={beat}><h2 className="pr-display">Build your<br/><em>first Gene.</em></h2><p className="pr-body">You don’t start by building a Genome.<br/>You start by encoding one decision worth inheriting.</p><Link className="pr-action" to={activityUrl('/build/gene')}>Build your first Gene →</Link></Reveal></div><Reveal at={3} beat={beat}><QR name="gene"/></Reveal></div>;
    case 18:return <><Label>One decision worth inheriting.</Label><h1 className="pr-title">One Gene.</h1><Orbit center="GENE" labels={['Intent','Authority','Representation','Relationships','Governance','Consumers']} beat={beat} base={2}/><p className="pr-body">Governance isn’t making every decision automatic. It’s making the boundary visible.</p></>;
    case 19:return <><h1 className="pr-title">From Gene to Genome.</h1><div className="pr-network"><svg viewBox="0 0 1408 260" aria-hidden="true">{[[160,120,160,235],[160,120,470,65],[160,120,490,210],[470,65,810,45],[470,65,810,190],[490,210,810,190],[810,45,1200,90],[810,190,1200,220]].map((p,i)=><path key={i} data-visible={beat>=2} d={`M${p[0]} ${p[1]} L${p[2]} ${p[3]}`}/>)}</svg>{['Gene',...domains].map((x,i)=><Reveal key={x} at={i===0?1:2} beat={beat} className={`pr-network-node pr-network-${i}`}><span>{x}</span></Reveal>)}</div><p className="pr-micro">Illustrative connections, not a required topology.</p><Reveal at={3} beat={beat}><p className="pr-statement">You don’t need to encode everything tomorrow.</p></Reveal><div className="pr-adoption">{['Start with high-value decisions.','Connect them.','Make them consumable where useful.','Govern the boundaries.'].map((text,i)=><Reveal key={text} at={i+4} beat={beat}><p className="pr-body">{text}</p></Reveal>)}</div><Reveal at={7} beat={beat}><p className="pr-label">The Genome can’t carry forward knowledge your organization never put into it.</p></Reveal></>;
    case 20:return <><Label>Forma revisited</Label><h1 className="pr-display">Now read the system<br/>through its decisions.</h1><Flow items={[{title:'One decision'},{title:'Connected knowledge'},{title:'Governed system'},{title:'Multiple consumers'}]}/><Reveal at={2} beat={beat}><p className="pr-statement">Design Genome is the methodology.<br/><em>Forma is one implementation.</em></p></Reveal></>;
    case 21:return <><Statement>Start with one decision<br/><em>worth inheriting.</em></Statement><div className="pr-closing-steps">{['Give it intent.','Give it authority.','Connect it.','Govern it.','Let it travel.'].map((x,i)=><Reveal key={x} at={i+2} beat={beat}><span>{x}</span></Reveal>)}</div></>;
    case 22:return <div className="pr-resource pr-final"><div><Label>The Design Genome</Label><h1 className="pr-display">Your design intelligence<br/>should outlive the tool<br/><em>consuming it.</em></h1><p className="pr-statement">design-genome.com</p><div className="pr-final-links"><a href="/framework" target="_blank" rel="noreferrer">Framework</a><a href="/reference" target="_blank" rel="noreferrer">Reference implementation</a><a href="/build/gene" target="_blank" rel="noreferrer">Build your first Gene</a><a href="https://github.com/ivanbarriga1984/design-genome" target="_blank" rel="noreferrer">GitHub</a></div><p className="pr-body">Ivan Barriga</p></div><QR name="home"/></div>;
    default:return null;
  }
}
